#include "light.h"

void lightInit(void){
  LIGHT_L1_OFF;
  LIGHT_L2_OFF;
  LIGHT_L3_OFF;
  LIGHT_L4_OFF;
  LIGHT_LC_OFF;
  LIGHT_LW_OFF;
  LIGHT_LR_OFF;
  LIGHT_LG_OFF;
  LIGHT_LB_OFF;

  
  GPIOA->MODER |= GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0 | GPIO_MODER_MODER2_0 | GPIO_MODER_MODER3_0;
  GPIOA->MODER |= GPIO_MODER_MODER4_0 | GPIO_MODER_MODER5_0 | GPIO_MODER_MODER6_0 | GPIO_MODER_MODER7_0;
  
  GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_0 | GPIO_OTYPER_OT_1 | GPIO_OTYPER_OT_2 | GPIO_OTYPER_OT_3);
  GPIOA->OTYPER |= GPIO_OTYPER_OT_4 | GPIO_OTYPER_OT_5 | GPIO_OTYPER_OT_6 | GPIO_OTYPER_OT_7;
  
  GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEEDR0 | GPIO_OSPEEDR_OSPEEDR1 | GPIO_OSPEEDR_OSPEEDR2 | GPIO_OSPEEDR_OSPEEDR3;
  GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEEDR4 | GPIO_OSPEEDR_OSPEEDR5 | GPIO_OSPEEDR_OSPEEDR6 | GPIO_OSPEEDR_OSPEEDR7;
  
  GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR0 | GPIO_PUPDR_PUPDR1 | GPIO_PUPDR_PUPDR2 | GPIO_PUPDR_PUPDR3);
  GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR4 | GPIO_PUPDR_PUPDR5 | GPIO_PUPDR_PUPDR6 | GPIO_PUPDR_PUPDR7);
  
  if(LIGHT_9 == true){
    GPIOF->MODER |= GPIO_MODER_MODER1_0;
    GPIOF->OTYPER &= ~GPIO_OTYPER_OT_1;
    GPIOF->OSPEEDR |= GPIO_OSPEEDR_OSPEEDR1;
    GPIOF->PUPDR &= ~GPIO_PUPDR_PUPDR1;
  }else{
    GPIOF->MODER &= ~GPIO_MODER_MODER1;
    GPIOF->PUPDR &= ~GPIO_PUPDR_PUPDR1;
  }
    GPIOF->MODER &= ~GPIO_MODER_MODER0;
    GPIOF->PUPDR &= ~GPIO_PUPDR_PUPDR0;
}
